channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - argparse==1.4.0
  - cffi==1.16.0
  - colorama==0.4.6
  - cytoolz==0.12.2
  - dask-expr==1.1.0
  - defusedxml==0.7.1
  - distributed==2024.5.0
  - jinja2==3.1.4
  - lightgbm==4.6.0
  - lz4==4.3.2
  - matplotlib==3.8.4
  - numpy==1.26.4
  - pandas==2.2.2
  - pyarrow==14.0.2
  - python-snappy==0.6.1
  - scikit-learn==1.4.2
  - scipy==1.13.1
  - zstandard==0.22.0
name: mlflow-env
